### ISSUE TITLE
no `log.info` method

### ISSUE THREAD

**Issue by Raynos** [clux/tap-pessimist#1]
I tried running the program and got this error

```
/Users/jakev/Uber/statsd-relay/node_modules/tap-pessimist/tapno.js:43
  log.info('output terminated - all ' + num + ' tests verified');
      ^
TypeError: Object #<Object> has no method 'info'
    at TapConsumer.<anonymous> (/Users/jakev/Uber/statsd-relay/node_modules/tap-pessimist/tapno.js:43:7)
    at TapConsumer.EventEmitter.emit (events.js:115:20)
    at TapConsumer.end (/Users/jakev/Uber/statsd-relay/node_modules/tap-pessimist/node_modules/tap/lib/tap-consumer.js:98:8)
    at Socket.onend (stream.js:66:10)
    at Socket.EventEmitter.emit (events.js:115:20)
    at Pipe.onread (net.js:416:51)
```

I might be that the logule interface changed

**Comment by clux** [comment]
Yeah, this was one of the earlier modules I wrote. Haven't actually touched this in ages because [tub](https://github.com/clux/tub) replaces it.

That said, maybe I should fix this up a little : )

**Comment by MadLittleMods** [comment]
I am getting a related issue:

```
TypeError: log.error is not a function
    at TapConsumer.<anonymous> (C:\Users\madli_000\AppData\Roaming\npm\node_modules\tap-pessimist\tapno.js:27:11)
    // ...
```

**Comment by clux** [comment]
Did a quick rewrite, module should be more sensible now.
